#![feature(ptr_sub_ptr, lazy_cell)]

pub mod combat;
pub mod database;
pub mod dialog;
pub mod eventsequence;
pub mod fade;
pub mod gamedata;
pub mod gamemessage;
pub mod gametime;
pub mod gameuserdata;
pub mod gameuserglobaldata;
pub mod gamevariable;
pub mod godpool;
pub mod language;
pub mod loadingmanager;
pub mod mapmind;
pub mod menu;
pub mod mess;
pub mod noticemanager;
pub mod pad;
pub mod proc;
pub mod resourcemanager;
pub mod script;
pub mod sequence;
pub mod singleton;
pub mod titlebar;
pub mod util;
pub mod vibrationmanager;
